USE [master]
GO
/****** Object:  Database [PF]    Script Date: 26/5/2022 19:36:58 ******/
CREATE DATABASE [PF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PF', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PF.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PF_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PF_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [PF] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PF] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PF] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PF] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PF] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PF] SET ARITHABORT OFF 
GO
ALTER DATABASE [PF] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PF] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PF] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PF] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PF] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PF] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PF] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PF] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PF] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PF] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PF] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PF] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PF] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PF] SET  MULTI_USER 
GO
ALTER DATABASE [PF] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PF] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PF] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PF] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PF] SET QUERY_STORE = OFF
GO
USE [PF]
GO
/****** Object:  Table [dbo].[Comentarios(Recetas)]    Script Date: 26/5/2022 19:36:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comentarios(Recetas)](
	[IdComentarios] [int] NOT NULL,
	[IdReceta] [int] NOT NULL,
	[IdUsuario] [int] NOT NULL,
	[Upvotes] [int] NOT NULL,
	[Downvotes] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Comentarios(Rutina)]    Script Date: 26/5/2022 19:36:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comentarios(Rutina)](
	[IdComentarios] [int] IDENTITY(1,1) NOT NULL,
	[IdRutina] [int] NOT NULL,
	[IdUsuario] [int] NOT NULL,
	[Comentario] [text] NOT NULL,
	[Upvotes] [int] NOT NULL,
	[Downvotes] [int] NOT NULL,
 CONSTRAINT [PK_Comentarios(Rutina)] PRIMARY KEY CLUSTERED 
(
	[IdComentarios] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Favoritos(receta)]    Script Date: 26/5/2022 19:36:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Favoritos(receta)](
	[IdUsuarios] [int] NOT NULL,
	[IdRecetas] [nchar](10) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Favoritos(Rutinas)]    Script Date: 26/5/2022 19:36:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Favoritos(Rutinas)](
	[IdUsuario] [int] NOT NULL,
	[IdRutinas] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recetas]    Script Date: 26/5/2022 19:36:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recetas](
	[IdRecetas] [int] NOT NULL,
	[IdNombre] [varchar](50) NOT NULL,
	[Descripcion] [varchar](50) NOT NULL,
	[Upvotes] [int] NOT NULL,
	[Downvotes] [int] NOT NULL,
	[Visitas] [int] NOT NULL,
	[Pasos] [text] NOT NULL,
	[Tiempo] [int] NOT NULL,
	[Dificultad] [int] NOT NULL,
	[CantCalorias] [int] NOT NULL,
	[IdUsuarios] [nchar](10) NOT NULL,
 CONSTRAINT [PK_Recetas] PRIMARY KEY CLUSTERED 
(
	[IdNombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rutinas]    Script Date: 26/5/2022 19:36:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rutinas](
	[IdRutina] [int] NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Tipo] [varchar](50) NOT NULL,
	[Descripcion] [varchar](50) NOT NULL,
	[Upvotes] [int] NOT NULL,
	[Downvotes] [int] NOT NULL,
	[Visitas] [int] NOT NULL,
	[Repeticiones] [int] NOT NULL,
	[Series] [int] NOT NULL,
	[ColorFondo] [binary](6) NOT NULL,
	[Favoritos] [binary](1) NOT NULL,
	[Pasos] [varchar](50) NOT NULL,
	[imagen] [varchar](50) NOT NULL,
	[FotoAnimada] [text] NOT NULL,
	[IdUsuario] [int] NOT NULL,
 CONSTRAINT [PK_Rutinas] PRIMARY KEY CLUSTERED 
(
	[IdRutina] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 26/5/2022 19:36:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Usuario] [varchar](50) NOT NULL,
	[Contraseña] [varchar](50) NOT NULL,
	[Foto] [text] NOT NULL,
	[ColorNombre] [binary](6) NOT NULL,
	[FotoAnimada] [binary](1) NOT NULL,
	[Monedas] [int] NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [PF] SET  READ_WRITE 
GO
