@api=http://localhost:4000/usuarios
@api2=http://localhost:4000/recetas
@api3=http://localhost:4000/rutinas
GET {{api}}
###
POST {{api}}
Content-Type: application/json

{
    "usuario":"pepito",
    "contraseña":"rodriguez"
}
###
GET {{api}}/1

###
DELETE {{api}}/2

###
GET {{api2}}
###
POST {{api2}}
Content-Type: application/json

{
    "NombreReceta":"papas al horno",
    "upvotes":0,
    "downvotes":0,
    "visitas":0,
    "descripcios":"papas al horno, ricos y faciles de hacer"
}
###
GET {{api2}}/1

###

DELETE {{api2}}/1
###
GET {{api3}}
